// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package decimaltools.actions;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.math.BigDecimal;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class ParseDecimal extends CustomJavaAction<java.math.BigDecimal>
{
	private java.lang.String Decimal;
	private java.lang.String Format;
	private java.lang.String DecimalSeparator;
	private java.lang.String GroupingSeparator;

	public ParseDecimal(IContext context, java.lang.String Decimal, java.lang.String Format, java.lang.String DecimalSeparator, java.lang.String GroupingSeparator)
	{
		super(context);
		this.Decimal = Decimal;
		this.Format = Format;
		this.DecimalSeparator = DecimalSeparator;
		this.GroupingSeparator = GroupingSeparator;
	}

	@java.lang.Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		// BEGIN USER CODE
		return parseDecimal(this.Decimal, this.Format, this.DecimalSeparator, this.GroupingSeparator);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ParseDecimal";
	}

	// BEGIN EXTRA CODE
	public java.math.BigDecimal parseDecimal(String decimal, String format, String decimalSeparator, String groupingSeparator)
	{
		// first do some sanity checks to make sure we have sensible data
		if (decimal == null || decimal.isBlank()) {
			throw new MendixRuntimeException("Decimal must not be blank");
		}
		if (format == null || format.isBlank()) {
			throw new MendixRuntimeException("Format must not be blank");
		}
		if (decimalSeparator == null) {
			throw new MendixRuntimeException("DecimalSeparator must not be empty");
		}
		if (groupingSeparator == null) {
			throw new MendixRuntimeException("GroupingSeparator must not be empty");
		}
		if (decimalSeparator.length() > 1) {
			throw new MendixRuntimeException("DecimalSeparator must be single character");
		}
		if (groupingSeparator.length() > 1) {
			throw new MendixRuntimeException("GroupingSeparator must be a single character");
		}

		DecimalFormatSymbols dfs = new DecimalFormatSymbols();
		dfs.setGroupingSeparator(groupingSeparator.charAt(0));
		dfs.setDecimalSeparator(decimalSeparator.charAt(0));
		DecimalFormat df = new DecimalFormat(format, dfs);
		df.setParseBigDecimal(true);
		BigDecimal parsedStringValue = null;
		try {
			parsedStringValue = (BigDecimal) df.parse(decimal);
		} catch (ParseException pe) {
			throw new MendixRuntimeException("Unable to parse decimal: " + pe.getMessage());
		}
		return parsedStringValue;
	}
	// END EXTRA CODE
}
